# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "areas", :primary_key => "gid", :force => true do |t|
    t.column "pref", :string, :limit => 20
    t.column "city1", :string, :limit => 20
    t.column "city2", :string, :limit => 20
    t.column "town1", :string, :limit => 20
    t.column "town2", :string, :limit => 20
    t.column "jcode", :integer
    t.column "p_num", :decimal
    t.column "h_num", :decimal
    t.column "flag1", :integer
    t.column "flag2", :integer
    t.column "the_geom", :multi_polygon, :srid => 4326
  end

  add_index "areas", ["the_geom"], :name => "areas_geom_index", :spatial=> true 

  create_table "walks", :force => true do |t|
    t.column "date", :date, :null => false
    t.column "start", :text, :null => false
    t.column "end", :text, :null => false
    t.column "length", :float
    t.column "path", :line_string, :srid => 4326
  end

  add_index "walks", ["path"], :name => "walks_path_index", :spatial=> true 

end
